### ISSUE TITLE
while approve loan application popup, loan tenure field is not showing

### ISSUE THREAD

**Issue by charan-inclusive-growth-chain** [charan-inclusive-growth-chain/IITD--workflow#5]

**Comment by charan-inclusive-growth-chain** [comment]
loan tenure field showing no value blank

**Comment by benpauligc** [comment]
Could you tell me which page this error appears in?

**Comment by charan-inclusive-growth-chain** [comment]
fpo node,  fpo loan tab, farmer loan , pending applications - while approve loan selected and click next next, in last window, the loan tenure value is not showing, its showing empty
