### ISSUE TITLE
Interest Rate API not working

### ISSUE THREAD

**Issue by benpauligc** [charan-inclusive-growth-chain/IITD--workflow#8]
When updating interest rate from fpo node -> farmer loan page, the put request works fine and it says request acknowledged.
But when applying for loan from farmer node, the interest rate is not updated. 
I'm using this api to pull interest rate value in farmer node -
/loanwindow/activeLoanWindow/farmer?fpoId=:fpoId

**Comment by charan-inclusive-growth-chain** [comment]
hello updated the API, now you will get a new fpoInterestRate field in the result object, you can use this field while creating new farmer laon, and the normal interest field while creating fpo loan , if you can check and confirm ill close this issue?

**Comment by benpauligc** [comment]
I don't see the new field. Please confirm whether this is the right api - http://13.232.131.203:3000/api/loanwindow/activeLoanWindow/farmer?fpoId=64817a37c31ad03a451a9f4c

**Comment by charan-inclusive-growth-chain** [comment]
{{host}}/loanwindow/activeLoanWindow/farmer?fpoId=64817a37c31ad03a451a9f4c

![image](https://github.com/charan-inclusive-growth-chain/IITD--workflow/assets/125336735/12e774ed-154d-4574-bbbc-530bfa198871)

**Comment by benpauligc** [comment]
![Screenshot from 2023-06-08 13-47-11](https://github.com/charan-inclusive-growth-chain/IITD--workflow/assets/117910071/4bb502fa-8307-48ee-b528-5ca6f861cdc1)
Mine still looks like this

**Comment by charan-inclusive-growth-chain** [comment]
it shouldnt be like that
can you, like make sure its not cachihg anywhere, logout and login prbably
